### ISSUE TITLE
For Sinzig data differences in both! directions

### ISSUE THREAD

**Issue by DirkSchmitt** [maxreb/Covid19Dashboard#1]
Hello!

I checked your values in https://covid19.reble.eu/Sinzig against my values (from 2.Dec.2020).
The Death count given in your data is related to the county (LK Ahrweiler and not  to the municipality.)
Also the „Inzidenz“ is not matching.

Table 3: Daten zur Stadt Sinzig aktuelle 7-Tages Inzidenz je 100.000 Einwohner 	136,1
aktuelle 14-Tages Inzidenz je 100.000 Einwohner 	311,9
maximale 7-Tages Inzidenz je 100.000 Einwohner 	374,3 am 12.11.2020
maximale 14-Tages Inzidenz je 100.000 Einwohner 	657,9 am 20.11.2020
Einwohner 	17630
Infektionen gesamt 	256
Infektionen aktiv 	76
Verstorben 	11

See also: https://user.computer42.org/~dirk/covid-19/Covid-19-LK-Ahrweiler.html
The data here is taken from the county announcements.

**Comment by maxreb** [comment]
Hi Dirk,

Yes, this behavoir is intended as the data is coming directly from the [RKI](https://npgeo-corona-npgeo-de.hub.arcgis.com/) and the RKI does only show data in the county (Landkreis, Kreisstadt or Bezirk) The county is shown below the city input field.

Nonetheless you are rigth, I have to visualize this with more precision. 

Thanks,
Max
